version: "3.9"

services:
  api:
    build: ./backend
    container_name: alvaresweb
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Postgres: Host=host.docker.internal;Port=5432;Database=alvares;Username=alvares;Password=supersecret
      ConnectionStrings__Mongo: mongodb://host.docker.internal:27017

  frontend:
    build: ./frontend/spa
    container_name: alvaresweb_frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - api
